controller_list:
  - name: fake_kol_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
initial:  # Define initial robot poses per group
  - group: kol
    pose: start