controller_list:
  - name: kol_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - arm_joint_1
      - arm_joint_2
      - arm_joint_3
      - arm_joint_4
      - arm_joint_5
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - gripper_finger_joint_l
      - gripper_finger_joint_r
  - name: mete
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      []